CREATE TABLE "users" (
                         "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "email" varchar not null unique ,
                         "password" varchar not null,
                         "team" varchar,
                         "role" int,
                         "position" int
);

CREATE TABLE IF NOT EXISTS apps
(
    app_id     INTEGER PRIMARY KEY,
    name   TEXT NOT NULL UNIQUE,
    secret TEXT NOT NULL UNIQUE
);